# prepare:
# 	for file in data/*.png; do convert -resize x400 $file $file; done
# 	for file in data/*.png; do optipng -quiet $file; done
# 
# apng: prepare
# 	# /kc is essential for the frames not to overlap
# 	apngasm out.png data/*.png /kc /kp
# 
# gif: prepare
# 	# <https://stackoverflow.com/a/23285387/353337>
# 	convert -dispose 2 -delay 10 -loop 0 data/*.png out.gif
# 
# webp: prepare
# 	img2webp data/*.png -min_size -lossy -o out.webp

mp4:
	ffmpeg -framerate 20 -i data/out%04d.png -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2:color=white" -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4
